// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/scalingo-operator/internal/usecases/database (interfaces: Manager)

// Package databasemock is a generated GoMock package.
package databasemock

import (
	context "context"
	reflect "reflect"

	domain "github.com/Scalingo/scalingo-operator/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CreateDatabase mocks base method.
func (m *MockManager) CreateDatabase(ctx context.Context, db domain.Database) (domain.Database, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDatabase", ctx, db)
	ret0, _ := ret[0].(domain.Database)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabase indicates an expected call of CreateDatabase.
func (mr *MockManagerMockRecorder) CreateDatabase(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabase", reflect.TypeOf((*MockManager)(nil).CreateDatabase), ctx, db)
}

// DeleteDatabase mocks base method.
func (m *MockManager) DeleteDatabase(ctx context.Context, dbID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDatabase", ctx, dbID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDatabase indicates an expected call of DeleteDatabase.
func (mr *MockManagerMockRecorder) DeleteDatabase(ctx, dbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDatabase", reflect.TypeOf((*MockManager)(nil).DeleteDatabase), ctx, dbID)
}

// DeleteDatabaseNetPeering mocks base method.
func (m *MockManager) DeleteDatabaseNetPeering(ctx context.Context, dbID, outscaleNetPeeringID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDatabaseNetPeering", ctx, dbID, outscaleNetPeeringID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDatabaseNetPeering indicates an expected call of DeleteDatabaseNetPeering.
func (mr *MockManagerMockRecorder) DeleteDatabaseNetPeering(ctx, dbID, outscaleNetPeeringID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDatabaseNetPeering", reflect.TypeOf((*MockManager)(nil).DeleteDatabaseNetPeering), ctx, dbID, outscaleNetPeeringID)
}

// EnsureDatabaseNetPeering mocks base method.
func (m *MockManager) EnsureDatabaseNetPeering(ctx context.Context, dbID, outscaleNetPeeringID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDatabaseNetPeering", ctx, dbID, outscaleNetPeeringID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDatabaseNetPeering indicates an expected call of EnsureDatabaseNetPeering.
func (mr *MockManagerMockRecorder) EnsureDatabaseNetPeering(ctx, dbID, outscaleNetPeeringID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDatabaseNetPeering", reflect.TypeOf((*MockManager)(nil).EnsureDatabaseNetPeering), ctx, dbID, outscaleNetPeeringID)
}

// GetDatabase mocks base method.
func (m *MockManager) GetDatabase(ctx context.Context, dbID string) (domain.Database, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabase", ctx, dbID)
	ret0, _ := ret[0].(domain.Database)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockManagerMockRecorder) GetDatabase(ctx, dbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockManager)(nil).GetDatabase), ctx, dbID)
}

// GetDatabaseEndpoints mocks base method.
func (m *MockManager) GetDatabaseEndpoints(ctx context.Context, dbID string) ([]domain.DatabaseEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseEndpoints", ctx, dbID)
	ret0, _ := ret[0].([]domain.DatabaseEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseEndpoints indicates an expected call of GetDatabaseEndpoints.
func (mr *MockManagerMockRecorder) GetDatabaseEndpoints(ctx, dbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseEndpoints", reflect.TypeOf((*MockManager)(nil).GetDatabaseEndpoints), ctx, dbID)
}

// GetDatabaseNetPeerings mocks base method.
func (m *MockManager) GetDatabaseNetPeerings(ctx context.Context, dbID string) ([]domain.DatabaseNetPeering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseNetPeerings", ctx, dbID)
	ret0, _ := ret[0].([]domain.DatabaseNetPeering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseNetPeerings indicates an expected call of GetDatabaseNetPeerings.
func (mr *MockManagerMockRecorder) GetDatabaseNetPeerings(ctx, dbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseNetPeerings", reflect.TypeOf((*MockManager)(nil).GetDatabaseNetPeerings), ctx, dbID)
}

// GetDatabaseNetworkConfiguration mocks base method.
func (m *MockManager) GetDatabaseNetworkConfiguration(ctx context.Context, dbID string) (domain.DatabaseNetworkConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseNetworkConfiguration", ctx, dbID)
	ret0, _ := ret[0].(domain.DatabaseNetworkConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseNetworkConfiguration indicates an expected call of GetDatabaseNetworkConfiguration.
func (mr *MockManagerMockRecorder) GetDatabaseNetworkConfiguration(ctx, dbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseNetworkConfiguration", reflect.TypeOf((*MockManager)(nil).GetDatabaseNetworkConfiguration), ctx, dbID)
}

// GetDatabaseURL mocks base method.
func (m *MockManager) GetDatabaseURL(ctx context.Context, db domain.Database) (domain.DatabaseURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseURL", ctx, db)
	ret0, _ := ret[0].(domain.DatabaseURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseURL indicates an expected call of GetDatabaseURL.
func (mr *MockManagerMockRecorder) GetDatabaseURL(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseURL", reflect.TypeOf((*MockManager)(nil).GetDatabaseURL), ctx, db)
}

// UpdateDatabase mocks base method.
func (m *MockManager) UpdateDatabase(ctx context.Context, dbID string, expectedDB domain.Database) (domain.DatabaseStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDatabase", ctx, dbID, expectedDB)
	ret0, _ := ret[0].(domain.DatabaseStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDatabase indicates an expected call of UpdateDatabase.
func (mr *MockManagerMockRecorder) UpdateDatabase(ctx, dbID, expectedDB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDatabase", reflect.TypeOf((*MockManager)(nil).UpdateDatabase), ctx, dbID, expectedDB)
}
